### ISSUE TITLE
deprecation_note brakes docstring processing

### ISSUE THREAD

**Issue by kmuehlbauer** [briancurtin/deprecation#10]
While joining the `function.__doc__`-string with the `deprecation_note`-string the indentation isn't handled properly. Let's look at this example:

```python
@deprecated(deprecated_in="0.0.3", removed_in="0.1.0",
            current_version="0.0.4",
            details="Do not use this function any more.")
def testfunc():
    """Test function.

    Returns
    -------
    name : str
        Some string
    """
    return "Teststring"

def newfunc():
    """Test function.

    Returns
    -------
    name : str
        Some string
    """
    return "Teststring"
```

Output of `help(testfunc)` (broken):

```
testfunc()
    Test function.
    
        Returns
        -------
        name : str
            Some string
        
    
    *Deprecated in 0.0.3, to be removed in 0.1.0. Do not use this function any more.*
```

Output of `help(newfunc)` (correct):

```
newfunc()
    Test function.
    
    Returns
    -------
    name : str
        Some string
```

The indentation of the function (numpy-style) docstring has been broken by the addition of the `deprecation_note`. While this might seem like a minor cosmetic issue, this breaks proper docstring processing in eg. `sphinx`.

**Comment by briancurtin** [comment]
It's not clear to me what the correction should look like. What would you expect the output of `help(testfunc)` to actually look like? I'm guessing you would want the `*Deprecated in ...` part indented in one level?

**Comment by kmuehlbauer** [comment]
It need to look like this:

```
testfunc()
    Test function.
    
    Returns
    -------
    name : str
        Some string

    *Deprecated in 0.0.3, to be removed in 0.1.0. Do not use this function any more.*
```

**Comment by kmuehlbauer** [comment]
The problem is, that the indentation of the `Return`-section is wrong after the `deprecation` is added to the function.

**Comment by briancurtin** [comment]
I wouldn't say it's *wrong* because it's doing what it intends to do, especially because in any other case indenting it is probably not going to be correct. Perhaps the `deprecated` decorator could gain a `format="{details}"` parameter where you could pass in `format="\t{details}"` to get it tabbed in one level, which could also be applied globally?

**Comment by kmuehlbauer** [comment]
It changes the indentation of the function-docstring in a way, that proper processing with `sphinx`(creation of apidoc) brakes. I would consider this behaviour *wrong*, but I will not argue too much. 

It's just that I have normal numpy style docstrings which are working perfect with the `sphinx-build` process. But when I add the `deprecated` decorator the workflow brakes.

**Comment by kmuehlbauer** [comment]
I see that arguing here is of no use. So let's proceed to your suggestion.

This is the status quo:

```python
            deprecation_note = ("*Deprecated{deprecated_in}{removed_in}"
                                "{period}{details}*".format(**parts))
            function.__doc__ = "\n\n".join([existing_docstring,
                                        deprecation_note])
```

Can you please be a bit more specific, where to add the `format`?

**Comment by briancurtin** [comment]
I was thinking that, for example, you would do something like this:

```python
import deprecation
deprecation.detail_format = "\t{details}" # A global way of setting the format

@deprecation.deprecated(deprecated_in="0.0.3", removed_in="0.1.0",
            current_version="0.0.4",
            details="Do not use this function any more.",
            detail_format="\t{details}" # This would override, but not needed if you set globally
)
def testfunc():
    """Test function.

    Returns
    -------
    name : str
        Some string
    """
    return "Teststring"
```

and behind the scenes that would do something like a `str.format` to give you a docstring like this:

```
testfunc()
    Test function.
    
        Returns
        -------
        name : str
            Some string

        *Deprecated in 0.0.3, to be removed in 0.1.0. Do not use this function any more.*
```

Would that work for you?

**Comment by kmuehlbauer** [comment]
@briancurtin I'll try as suggested at first light tomorrow. But I have the gut feeling, that we will have to dig a bit deeper. Anyway, your help is very much appreciated.

**Comment by heistermann** [comment]
First of all, thanks for addressing this issue. I *think* the way the deprecation note is inserted does not only conflict with numpydoc conventions, but with [PEP 257](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings) docstring conventions, too. For multiline docstrings PEP257 states that "the entire docstring is indented the same as the quotes at its first line (see example below)." It also says that 

> Docstring processing tools will strip a uniform amount of indentation from the second 
> and further lines of the docstring, equal to the minimum indentation of all non-blank lines 
> after the first line. Any indentation in the first line of the docstring (i.e., up to the first newline) 
> is insignificant and removed. Relative indentation of later lines in the docstring is retained.

Consider I have a one line docstring like in your foo example:

```
@deprecation.deprecated(deprecated_in="1.0", removed_in="2.0",
                        current_version="1.0",
                        details="Use the bar function instead")
def foo():
    """Do some stuff"""
    return 1

print(foo.__doc__)
```

gives output

```
Do some stuff

*Deprecated in 1.0, to be removed in 2.0. Use the bar function instead*
```

which is ok.

But if the function (docstring) looks like this (in accordance with PEP 257):

```
@deprecation.deprecated(deprecated_in="1.0", removed_in="2.0",
                        current_version="1.0",
                        details="Use the bar function instead")
def foo():
    """Do some stuff
    
    More doc info.
    """
    return 1

print(foo.__doc__)
```

will give us

```
Do some stuff
    
    More doc info.
    

*Deprecated in 1.0, to be removed in 2.0. Use the bar function instead*
``` 

which is not desired because in the multi-line docstring, there should be one level of indentation below the so called "summary line".

What it should look like, imho, is  

```
Do some stuff
    
    More doc info.
    

    *Deprecated in 1.0, to be removed in 2.0. Use the bar function instead*
``` 

Hope I got this right...what do you think?

**Comment by briancurtin** [comment]
@kmuehlbauer what I wrote there doesn't actually work yet, it was just pseudo-code. However, based on what @heistermann just said, perhaps what you were originally asking about should Just Work.

I'll take a further look into it, but based on that it seems like this should be pretty easy to fix and doesn't need any sort of options.

**Comment by kmuehlbauer** [comment]
@heistermann Thanks for bringing up PEP257. Now I see, why the indentation run havoc. 

@briancurtin The less options, the better. But, one thing we could think about is, giving this deprecation note a docstring header, like "Notes" or "Warning" or some user defined.

**Comment by briancurtin** [comment]
@kmuehlbauer I created #11 for that so this can just stay focused on getting the indentation stuff sorted out independently.

**Comment by briancurtin** [comment]
FYI I have a fix in progress for this. Still working a couple of things out so it works consistently whether you have your closing """ on the same line as the last sentence or on its own line, but I should have it up as PR probably tomorrow morning (New York time).

**Comment by briancurtin** [comment]
This is now released in version 1.2: https://pypi.org/project/deprecation/1.2/

**Comment by kmuehlbauer** [comment]
@briancurtin Great!

**Comment by briancurtin** [comment]
Thanks for the report and helping figure it out!
