### ISSUE TITLE
Use the `.. deprecated:: <version>` directive

### ISSUE THREAD

**Issue by briancurtin** [briancurtin/deprecation#11]
Perhaps the decorator should use the `deprecated` directive. See http://www.sphinx-doc.org/en/stable/markup/para.html#directive-deprecated

Note: I was originally going to use that but did not for some reason, and I can't remember why. I think it had to do with an old project I was building this for at the time not supporting that directive?

**Comment by kmuehlbauer** [comment]
Using deprecated directive would be a neat solution, imho.

**Comment by kmuehlbauer** [comment]
Would it be possible, to have this deprecated directive directly after the header line? I mean header line, empty line, deprecation directive, empty line, rest of docstring. For long docstring the user gets the deprecation information at the very beginning. Makes sense?

**Comment by kmuehlbauer** [comment]
@briancurtin Are you already working on this? I'm currently testing some additions, could open a PR if you are interested.

**Comment by briancurtin** [comment]
I was about to get started on it, but if you want to go ahead and open a PR when you're ready that'd be great. I'll take a look and help out however I can.

**Comment by briancurtin** [comment]
This was fixed in #15
