### ISSUE TITLE
Merge this functionality into https://github.com/openstack/debtcollector ?

### ISSUE THREAD

**Issue by harlowja** [briancurtin/deprecation#28]
Seems like some overlap here, maybe could be merged?

**Comment by harlowja** [comment]
https://docs.openstack.org/debtcollector/latest/reference/index.html#module-debtcollector (some docs); I was a part of creating that lib, and this one loooks pretty nearly the same(ish). That isn't bad, just seems like they could share/be the same?

**Comment by briancurtin** [comment]
If this library has something you want, feel free to take it. I'm fine with this living on as it is, though.
