### ISSUE TITLE
fail_if_not_removed hides tests from nose runner

### ISSUE THREAD

**Issue by radeklat** [briancurtin/deprecation#30]
Unit tests marked with the `fail_if_not_removed` decorator are not discovered by nose, because the test methods are renamed by the decorator to `_inner` and that does not match the default nose pattern.

Tested solution:
In `fail_if_not_removed`, return `test_inner` instead of `_inner`.

**Comment by radeklat** [comment]
Created PR: https://github.com/briancurtin/deprecation/pull/31

**Comment by gabbard** [comment]
This issue appears to have been closed by #31.
