### ISSUE TITLE
Include documentation in PyPI tarballs

### ISSUE THREAD

**Issue by sbraz** [briancurtin/deprecation#39]
Hello,
Would it be possible to include the `docs ` folder in PyPI tarballs? We at Gentoo usually rely on those to build the documentation.

**Comment by briancurtin** [comment]
Thanks for raising this and submitting a PR! I'll get a new release out and update you here once it's out.

**Comment by sbraz** [comment]
Thanks!

**Comment by briancurtin** [comment]
https://pypi.org/project/deprecation/2.0.7/ is now out, and 248fe63 is the `2.0.7` tag if that matters.
