### ISSUE TITLE
fail_if_not_removed interferes with pytest fixtures

### ISSUE THREAD

**Issue by domdfcoding** [briancurtin/deprecation#42]
Decorating a test with `fail_if_not_removed` when the test expects a pytest fixture causes a `TypeError` due to a missing argument.

For example:

```
@deprecation.fail_if_not_removed
def test_get_pt_bounds(peak):
    peak.get_pt_bounds()
```

Results in:
```FAILED
../../../../.local/lib/python3.6/site-packages/deprecation.py:264 (test_get_pt_bounds)
args = (), kwargs = {}, caught_warnings = []

    def test_inner(*args, **kwargs):
        with warnings.catch_warnings(record=True) as caught_warnings:
            warnings.simplefilter("always")
>           rv = method(*args, **kwargs)
E           TypeError: test_get_pt_bounds() missing 1 required positional argument: 'peak'

/home/domdf/.local/lib/python3.6/site-packages/deprecation.py:268: TypeError
```

From the documentation I can't see an alternative way to pass the fixture to the test

**Comment by briancurtin** [comment]
Interesting. I don't know anything about pytest or how it does fixtures, so not really sure what to do here off the top of my head.

**Comment by gabbard** [comment]
@briancurtin : [This answer on StackOverflow](https://stackoverflow.com/a/19614807/413345) suggests this problem can be fixed by using [the decorator package](https://pypi.org/project/decorator/) (or, presumably, manually doing whatever that package does).  

If the simpler solution of introducing a dependency on `decorator` is acceptable, I have a student I could ask to fix this.

**Comment by briancurtin** [comment]
I don't think it's worth adding a dependency to solve this as it seems to be narrowly scoped to pytest, so I'd rather it be solved independently.

**Comment by domdfcoding** [comment]
I have tried the suggestion from @gabbard and it works with my pytest tests, but it doesn't play nice with `unittest2` and so `deprecation`'s tests fail. 

However, decorating `test_inner` with `functools.wraps(method)` (as per the other answer to the SO question) seems to work just as well and doesn't break `deprecation`'s tests.
