### ISSUE TITLE
PyPi v2.1 released, no corresponding GitHub release

### ISSUE THREAD

**Issue by drewrisinger** [briancurtin/deprecation#49]
When looking at upgrading this package in https://github.com/NixOS/nixpkgs/pull/87100,
I noticed that [PyPi has a v2.1 for this package](https://pypi.org/project/deprecation/2.1.0/), but there's no corresponding release here. Is the PyPi release a mistake or malicious?

**Comment by briancurtin** [comment]
It was intentional—forgot to create/push the tag. https://github.com/briancurtin/deprecation/releases/tag/2.1.0

**Comment by drewrisinger** [comment]
Is there a changelog for this release?

**Comment by briancurtin** [comment]
No one's ever asked for that, so not right now. In lieu of that, this project doesn't do branching and is just tags off of master, so https://github.com/briancurtin/deprecation/commits/master is effectively the same thing. I could start keeping a changelog if that's wanted.

**Comment by drewrisinger** [comment]
Just was curious, I was looking at packaging a package that required deprecation < 2.1, and was curious if there were any updates/deprecations in this package that could break the other package.

**Comment by drewrisinger** [comment]
Honestly, I don't need the changelog, and chances are slim that I'll need to return to this package again, so don't put much stock in my "request".
