### ISSUE TITLE
Question: looking for future_warning

### ISSUE THREAD

**Issue by zillionare** [briancurtin/deprecation#52]
How can I apply a future_warning? I need to warn user that some API are not stable, and prone to change later

**Comment by briancurtin** [comment]
That's something I think you should solve in your documentation, or possibly by using [`warnings.warn`](https://docs.python.org/3/library/warnings.html#warnings.warn) in your code. What you're trying to do is outside the scoe of this project, though.

```python3
>>> import warnings
>>> warnings.warn("This API is not stable and may change in the future")
<stdin>:1: UserWarning: This API is not stable and may change in the future
```
